#!/usr/bin/env bash
# this will help me transport files to a remote server

if (( $# < 3 )); then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

elif (( $# == 3 )); then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"

elif (( $# == 4 )); then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"

else
    echo "Invalid number of parameters"
fi
