#!/usr/bin/env bash
# this will help me transport files to a remote server

if (( $# < 3 )); then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

# Check if PATH_TO_SSH_KEY is provided, otherwise use the default path

SSH_KEY=""
if (( $# == 4 )); then
    SSH_KEY="-i $4"
fi

scp -o StrictHostKeyChecking=no $SSH_KEY "$1" "$3@$2:~/"
