#!/usr/bin/env bash
# this is to install NGINX server !

# Update package list
sudo apt-get update
# Install NGINX
sudo apt-get install -y nginx
# hi world
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
# start the server
sudo service nginx start
