#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the
# requirements asked in this task

# installing nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Creating a simple HTML page
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Add redirection rule to NGINX configuration
sed -i '42i\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default

# Reload NGINX to apply changes
sudo service nginx reload

# Start NGINX service
sudo service nginx start
