#!/usr/bin/env bash
# error 404 

# installing nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Creating a simple HTML page
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sh -c 'echo "Ceci n'est pas une page" > /var/www/html/404.html

# Adding redirection
sed -i '42i\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a \\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Reload NGINX to apply changes
sudo service nginx reload

# Start NGINX service
sudo service nginx start
