#!/usr/bin/env bash
# i used my previous script and worked on the task

apt-get update
apt-get -y install nginx apt-transport-https ufw

ufw allow 'Nginx HTTP'

HOST_NAME=$(hostname)

HEADER="\\\n\tadd_header X-Served-By \"$HOST_NAME\";\n"
FIND=$(grep "X-Served-By" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

echo "Hello World!" > /var/www/html/index.html

FIND=$(grep "location /redirect_me" /etc/nginx/sites-available/default)
STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
    sed -i "/listen \[::\]:80 default_server;/a $STRING" /etc/nginx/sites-available/default
fi

FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sed -i "40i $ERROR" /etc/nginx/sites-available/default
fi

nginx -t
service nginx restart
