#!/usr/bin/env bash
# Configures a new Ubuntu machine with custom HTTP response header and redirection
# Using the previous script with additional custom header configuration
# Ignoring SC2154 for shellcheck
apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
hostname="$(hostname)"
echo "
server {
        listen 80;
        listen [::]:80;

        server_name _;

        error_page 404 /404.html;
        add_header X-Served-By $hostname;

        location / 
	{
            root /var/www/html;
            index index.html;
        }

        location /redirect_me 
	{
            return 301 https://www.github.com/Cha1mae;
        }

        location /404 
	{
            root /var/www/html;
            internal;
        }
}
" >/etc/nginx/sites-available/default
service nginx restart
