#!/usr/bin/env bash
# configuring a new Ubuntu machine with Nginx,
# a custom HTTP response header and a redirection,
# i used my previous script used for the past project
# ignoring SC2154 for shellcheck

# Update packages
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Creating a simple HTML page
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sh -c 'echo "Ceci n'\''est pas une page" > /var/www/html/404.html'

# Get the hostname of the server
HOSTNAME=$(462500-web-01)

# Configure Nginx
sudo tee /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By "$HOSTNAME";
    location / {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
}
EOF

# Reload NGINX to apply changes
sudo service nginx reload

# Start NGINX service
sudo service nginx start
