#!/usr/bin/env bash
#Installing and configuring HAproxy on the lb-01 server.

# Installing HAProxy and configure for two servers
apt-get update
apt-get -y install haproxy=1.8.*

# Enabling HAProxy in init script
echo "ENABLED=1" >> /etc/default/haproxy

# ip adresses
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 462500-web-01 52.91.152.110:80 check\n\tserver 462500-web-02 52.87.152.252:80 check' /etc/haproxy/haproxy.cfg

# Restarting
systemctl restart haproxy
