#!/bin/bash
# nchofo had proxy kidayr, second try the charm

# Install HAproxy
if ! command -v haproxy &> /dev/null; then
    sudo apt install -y software-properties-common
    sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
    sudo apt update
    sudo apt install -y haproxy=1.8.*
fi

# Configure HAproxy
load_balancer="\nfrontend http\n
    bind *:80
    mode http
    default_backend load_b

backend load_b\n
    balance roundrobin
    server web-01 52.91.152.110:80 check
    server web-02 52.87.152.252:80 check
"

# Enable HAproxy init script
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$load_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo systemctl restart haproxy
