#!/usr/bin/env bash
# i tried everything please work

sudo apt-get update
sudo apt-get install -y nginx
new="80 default_server"
old="8080 default_server"
sudo sed -i "s/$old/$new/" /etc/nginx/sites-enabled/default
sudo service nginx start
