#!/usr/bin/env bash
# no need to download Nginx since I already have it
# well, I just connected it to port 80 and restarted Nginx

service nginx start
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
