#!/usr/bin/env bash
# This script is displaying gl bl

superstition=1
while [ $superstition -le 20 ]
do
    echo $superstition
    case $superstition in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    superstition=$(( superstition + 1 ))
done
