#!/usr/bin/env bash
# well see if this simpple and sweet
service apache2 stop
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
service nginx restart
